"""Initial migration: create bordereaux_files and bordereaux_rows tables

Revision ID: 3155dc5df8b1
Revises: 
Create Date: 2025-11-18 21:25:45.640997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3155dc5df8b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bordereaux_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RECEIVED', 'NEW_TEMPLATE_REQUIRED', 'PROCESSING', 'PROCESSED_OK', 'PROCESSED_WITH_ERRORS', 'COMPLETED', 'FAILED', name='filestatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('processed_rows', sa.Integer(), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proposal_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bordereaux_files_filename'), 'bordereaux_files', ['filename'], unique=False)
    op.create_index(op.f('ix_bordereaux_files_id'), 'bordereaux_files', ['id'], unique=False)
    op.create_index(op.f('ix_bordereaux_files_status'), 'bordereaux_files', ['status'], unique=False)
    op.create_index(op.f('ix_bordereaux_files_sender'), 'bordereaux_files', ['sender'], unique=False)
    op.create_index(op.f('ix_bordereaux_files_file_hash'), 'bordereaux_files', ['file_hash'], unique=False)
    op.create_table('bordereaux_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=True),
    sa.Column('insured_name', sa.String(length=255), nullable=True),
    sa.Column('inception_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('premium_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.Enum('USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY', 'CHF', 'ZAR', 'NGN', 'GHS', 'KES', name='currency'), nullable=True),
    sa.Column('claim_amount', sa.Float(), nullable=True),
    sa.Column('commission_amount', sa.Float(), nullable=True),
    sa.Column('net_premium', sa.Float(), nullable=True),
    sa.Column('broker_name', sa.String(length=255), nullable=True),
    sa.Column('product_type', sa.String(length=100), nullable=True),
    sa.Column('coverage_type', sa.String(length=100), nullable=True),
    sa.Column('risk_location', sa.String(length=255), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['bordereaux_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bordereaux_rows_expiry_date'), 'bordereaux_rows', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_bordereaux_rows_file_id'), 'bordereaux_rows', ['file_id'], unique=False)
    op.create_index(op.f('ix_bordereaux_rows_id'), 'bordereaux_rows', ['id'], unique=False)
    op.create_index(op.f('ix_bordereaux_rows_inception_date'), 'bordereaux_rows', ['inception_date'], unique=False)
    op.create_index(op.f('ix_bordereaux_rows_policy_number'), 'bordereaux_rows', ['policy_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bordereaux_rows_policy_number'), table_name='bordereaux_rows')
    op.drop_index(op.f('ix_bordereaux_rows_inception_date'), table_name='bordereaux_rows')
    op.drop_index(op.f('ix_bordereaux_rows_id'), table_name='bordereaux_rows')
    op.drop_index(op.f('ix_bordereaux_rows_file_id'), table_name='bordereaux_rows')
    op.drop_index(op.f('ix_bordereaux_rows_expiry_date'), table_name='bordereaux_rows')
    op.drop_table('bordereaux_rows')
    op.drop_index(op.f('ix_bordereaux_files_file_hash'), table_name='bordereaux_files')
    op.drop_index(op.f('ix_bordereaux_files_sender'), table_name='bordereaux_files')
    op.drop_index(op.f('ix_bordereaux_files_status'), table_name='bordereaux_files')
    op.drop_index(op.f('ix_bordereaux_files_id'), table_name='bordereaux_files')
    op.drop_index(op.f('ix_bordereaux_files_filename'), table_name='bordereaux_files')
    op.drop_table('bordereaux_files')
    # ### end Alembic commands ###

