"""Create templates table

Revision ID: 4c5123e36830
Revises: 3155dc5df8b1
Create Date: 2025-11-18 22:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c5123e36830'
down_revision = '3155dc5df8b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('carrier', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=True),
    sa.Column('column_mappings', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('active_flag', sa.Boolean(), nullable=False),
    sa.Column('json_file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_id'), 'templates', ['id'], unique=False)
    op.create_index(op.f('ix_templates_template_id'), 'templates', ['template_id'], unique=True)
    op.create_index(op.f('ix_templates_file_type'), 'templates', ['file_type'], unique=False)
    op.create_index(op.f('ix_templates_active_flag'), 'templates', ['active_flag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_templates_active_flag'), table_name='templates')
    op.drop_index(op.f('ix_templates_file_type'), table_name='templates')
    op.drop_index(op.f('ix_templates_template_id'), table_name='templates')
    op.drop_index(op.f('ix_templates_id'), table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###

