"""Create validation errors table

Revision ID: e80068eedf9e
Revises: 4c5123e36830
Create Date: 2025-11-18 23:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e80068eedf9e'
down_revision = '4c5123e36830'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bordereaux_validation_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.Column('rule_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['bordereaux_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bordereaux_validation_errors_id'), 'bordereaux_validation_errors', ['id'], unique=False)
    op.create_index(op.f('ix_bordereaux_validation_errors_file_id'), 'bordereaux_validation_errors', ['file_id'], unique=False)
    op.create_index(op.f('ix_bordereaux_validation_errors_error_code'), 'bordereaux_validation_errors', ['error_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bordereaux_validation_errors_error_code'), table_name='bordereaux_validation_errors')
    op.drop_index(op.f('ix_bordereaux_validation_errors_file_id'), table_name='bordereaux_validation_errors')
    op.drop_index(op.f('ix_bordereaux_validation_errors_id'), table_name='bordereaux_validation_errors')
    op.drop_table('bordereaux_validation_errors')
    # ### end Alembic commands ###

